# Image used by AWS for lambda python
FROM public.ecr.aws/lambda/python:3.13

# Add tar used by VSCode
RUN dnf install -y tar gzip \
 && dnf clean all

# Copy requirements.txt
COPY requirements-dev.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements-dev.txt

# or copy all code from a  directory
COPY src/ ${LAMBDA_TASK_ROOT}/src/
COPY test/ ${LAMBDA_TASK_ROOT}/test/
COPY lambda_function.py ${LAMBDA_TASK_ROOT}

ENV PYTHONPATH=${LAMBDA_TASK_ROOT}
# Override Lambda entrypoint
ENTRYPOINT []
# Default command: run tests
CMD ["pytest", "--maxfail=1", "--disable-warnings"]